#BUILD
FROM maven:3-jdk-11 as builder
RUN mkdir -p /build
WORKDIR /build
COPY pom.xml /build
RUN mvn -B dependency:resolve dependency:resolve-plugins
COPY src /build/src
RUN mvn package -DskipTests

#RUN
FROM "openjdk:11-jdk"
MAINTAINER Marcos Mele
COPY --from=builder /build/target/*.jar starwars.jar
ARG ambiente
ENV envambiente=${ambiente}
ENTRYPOINT ["java", "-Dspring.profiles.active=${envambiente}", "-jar", "/starwars.jar"]